[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

# Remappings
remappings = [
    "valantis-core/=lib/valantis-core/src/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "lib/valantis-core/lib/openzeppelin-contracts/=lib/openzeppelin-contracts/",
]

[rpc_endpoints]
hyperevm = "${HYPEREVM_RPC_URL}"
hyperevm_testnet = "https://rpc.hyperliquid-testnet.xyz/evm"

[etherscan]
hyperevm = { key = "${ETHERSCAN_KEY}", url = "https://hyperliquid.cloud.blockscout.com/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
